### ISSUE TITLE
The mean and median

### ISSUE THREAD

**Issue by aalzres** [aalzres/portfolio#13]
### Description

Write a simple app with 2 main features. This app should support calculating the mean and median of a set of numbers. The emphasis should be on creating a frictionless and seamless user experience. Please do not use the built-in keyboard for this task.

### Check List

- [X] A frictionless and seamless user experience
- [X] The mean of a set of numbers
- [X] The median of a set of numbers

### Subtask

- [New SPM Statistic](https://github.com/aalzres/portfolio/pull/15)
- [Implement Mean test](https://github.com/aalzres/portfolio/pull/15)
- [Implement Median test](https://github.com/aalzres/portfolio/pull/17)
- [Implement layout for StatisticModule](https://github.com/aalzres/portfolio/pull/19) - [Design](https://www.figma.com/file/pg5R0IIdNdX0VZP1fs7iQm/iOS-App-Wireframes-(Community)?node-id=259%3A915)
- [Implement logic for StatisticModule](https://github.com/aalzres/portfolio/pull/22)
